### ISSUE TITLE
targetcmp unit test fail for mipseb/mipsel

### ISSUE THREAD

**Issue by AndrewFasano** [rehosting/penguin#13]
In the [unit tests on the iter branch](https://github.com/panda-re/penguin/tree/iter/unittest) the test for `env_cmp` fails for both mipsel and mipseb.

In this test we set an environment variable to the magic `DYNVALDYNVALDYNVAL` and the env plugin loads the [panda targetcmp plugin](https://github.com/panda-re/panda/tree/dev/panda/plugins/targetcmp) to detect values this constant might be compared against.

This works for armel, but fails for MIPS. The targetcmp plugin does seem to work (at least a little) on mips so I'm not positive what's going wrong. Is it issues with virtual memory/paging that often shows up for mips? Or is there a more straightforward bug here? I tested the basic functionality with plain old pypanda  and a mips guest and everything worked fine:

```sh
$(python3 -m pandare.qcows mips) -panda callstack_instr:stack_type=asid -panda callwitharg:targets=DYNVALDYNVAL,verbose=1 -panda targetcmp:target_str=DYNVALDYNVALDYNVAL

root@debian-mips:~# export foo=DYNVALDYNVAL
Found string target DYNVALDYNVAL in call at 00417170. In argument 0
Found string target DYNVALDYNVAL in call at 00417170. In argument 1
Found string target DYNVALDYNVAL in call at 00417170. In argument 0
Found string target DYNVALDYNVAL in call at 00417170. In argument 1

root@debian-mips:~# R=$(env | grep foo | sed -e "s/.foo=//" -e s/^.*=//)
Found string target DYNVALDYNVAL in call at 00417170. In argument 0
Found string target DYNVALDYNVAL in call at 00417170. In argument 0
Found string target DYNVALDYNVAL in call at 0044b600. In argument 0

root@debian-mips:~# [ "$R" == "foo" ]
Found string target DYNVALDYNVAL in call at 0044ab70. In argument 0
root@debian-mips:~# QEMU 2.9.1 monitor - type 'help' for more information
(qemu) q
(venv) andrew@panda194:~/git/panda$ cat targetcmp.txt
foo
DYNVALDYNVAL
R
```

But when we run the unit test, the  string `target` doesn't show up in any of the `results/env*` files. Even if we manually set the init script to basically be the same as above, there's no result:
```yaml
  /init:
    type: file
    contents: |
      #!/igloo/utils/sh
      set -eux
      #
      # Env test
      export foo=DYNVALDYNVALDYNVAL
      R=$(/igloo/utils/busybox env | /igloo/utils/busybox grep foo | /igloo/utils/busybox sed -e "s/.foo=//" -e s/^.*=//)
      [ "$R" == "target" ]
```
