### ISSUE TITLE
Configurations are too verbose

### ISSUE THREAD

**Issue by lacraig2** [rehosting/penguin#185]
The average default configuration length in my projects directory is 1025 lines.

This seems like too much. In particular, I think it makes it more challenging to focus on the parts of the config that are important.

I have two thoughts on how we could better focus these.

The first is that we could make the config the user writes a trimmed config. This would mean that many of the default values that we supply are added after the fact. We would do so in a way that if the user requested a value different from the default we would keep the user value. Further, we would write a full configuration to the run directory so they can see how it resulted.

The second is putting more parts of the configuration in separate files. I know the general idea was that configurations are self-contained, but realistically they at least require a filesystem. The following are some thoughts on how we could apply these

For `/igloo/init` we could very reasonably be brought in as `./base/init`.

For our implementation of keys on the system we could consider using files relative to the configuration. There is a project called pyyaml-include that makes an "include" syntax available with yaml: https://github.com/tanbro/pyyaml-include

For example, the following 114 lines of our configuration establish that there are a bunch of key related things:
```yaml
  /igloo/keys/:
    type: dir
    mode: 493
  /igloo/keys/rsa4096.pem:
    type: host_file
    host_path: /pkg/resources/static_keys/rsa4096.pem
    mode: 292
  /igloo/keys/rsa2048.pem:
    type: host_file
    host_path: /pkg/resources/static_keys/rsa2048.pem
    mode: 292
  /igloo/keys/make_keys.sh:
    type: host_file
    host_path: /pkg/resources/static_keys/make_keys.sh
    mode: 292
  /igloo/keys/ssh.rsa.pub:
    type: host_file
    host_path: /pkg/resources/static_keys/ssh.rsa.pub
    mode: 292
[96 more lines]
```

Instead of this we could do something like:

```yaml
static_files:
    - !include ./base/keys.yaml
```
