### ISSUE TITLE
Upgrade to yaml 1.2

### ISSUE THREAD

**Issue by lacraig2** [rehosting/penguin#189]
The project https://pypi.org/project/yamlcore/ implements yaml 1.2 which extends the feature set of PyYAML.

This would get us additional features. The one I had in mind is octal numbers (see issue: https://github.com/yaml/pyyaml/issues/608)

In practice, this would mean we could take what we're currently using:
```
  /igloo/utils/strace:
    type: host_file
    host_path: /igloo_static/utils.bin/strace.mipsel
    mode: 493
```

with a mode of 493 (which maybe you can understand, but I can't by just reading it) into:

```
  /igloo/utils/strace:
    type: host_file
    host_path: /igloo_static/utils.bin/strace.mipsel
    mode: 0o755
```

Which is a set of file permissions that I can understand.
