### ISSUE TITLE
Regression in stride rehosting

### ISSUE THREAD

**Issue by AndrewFasano** [rehosting/penguin#199]
The stride firmware used to rehost enough for the webserver to work with the following changes to the default config 

```
env:
  igloo_init: /sbin/init
  sxid: 0150_5MS-MDM-1
pseudofiles:
  /dev/dsa:
    ioctl:
      "*":
        model: return_const
        val: 0
```

Now it seems like it's not getting the SXID value, even though we're passing it through the kernel args.
```
curl -u admin:admin 192.168.1.2/cgi-bin/menubar.cgi
No configuration for SXID '0190_???'
```

I statically looked at the library that implements the SXID lookup and it reads a fixed size buffer from /proc/cmdline, but even with all our extra junk in there, the sxid value seems like it should be read. Unrelated to this issue, perhaps we should consider changing how we pass data to guest utilities to avoid future issues when existing guest utilities have hardcoded expectations about /proc/cmdline max lengths.
