### ISSUE TITLE
Pseudofiles `from_file` model should be use project-relative paths

### ISSUE THREAD

**Issue by AndrewFasano** [rehosting/penguin#350]
Right now if we want to use the `from_file` model in a device under `pseudofiles`, we have to specify an absolute *in-container* path which is confusing as we typically hide the container filesystems from a user. Furthermore it's confusingly inconsistent as the `static_files` section uses project-directory relative host paths.

(Note that the `kernel` option is still an absolute, in-container path as we don't want to copy kernels into every project directory - it's kind of useful for dev and prototyping, but perhaps it should just be the kernel name and auto-load that from the fixed path `/igloo_static/kernels/<kernel_version>/<kernel_arch_name>`)

Current:
```yaml
pseudofiles:
  /proc/myproc:
    read:
      model: from_file
      filename: /host_projects/your_firmware_name/your_filename
```

Proposed:
```yaml
pseudofiles:
  /proc/myproc:
    read:
      model: from_file
      filename: your_filename
```

The downside here is that we couldn't reference non-project files, but I'm not sure if that's something we'd ever want to do.
