### ISSUE TITLE
Make kernel and fs path optional

### ISSUE THREAD

**Issue by lacraig2** [rehosting/penguin#404]
Right now configs have this at the top:

```yaml
core:
  arch: armel
  kernel: /igloo_static/kernels/4.10/zImage.armel
  fs: ./base/fs.tar.gz
  root_shell: true
  show_output: false
  strace: false
  ltrace: false
  version: 1.0.0
```

I think we should be allowed to set `kernel` and `fs`, but right now it's so unlikely to happen I think making these default values and supplying the obvious values would make more sense.
