### ISSUE TITLE
Proposal: static_files grouped by type

### ISSUE THREAD

**Issue by lacraig2** [rehosting/penguin#434]
static_files currently features the following types: inline_file host_file, dir, symlink, dev, delete, move

They look like this:
```yaml
static_files:
    /file:
          type: some_type
          arg1: val1
          arg2: val2
```

I'd be interested in exploring a format where they were grouped by type:

```yaml
static_files:
      host_file:
            /igloo/utils/vpn: /igloo_static/vpn/vpn.mipseb
            /igloo/utils/asdf:
                    host_path: /igloo_static/asdf
                    mode: 493
```

Here we see two formats for host_file where it can either accept a file mapping (with a default mode) or a dictionary with additional options.

This option has the advantage of being backwards compatible.
