### ISSUE TITLE
Proposal: More extensible pseudofiles

### ISSUE THREAD

**Issue by lacraig2** [rehosting/penguin#438]
**Is your feature request related to a problem? Please describe.**

Pseudofiles offers some nice models, but often devices require more involved models.

We often get around these issues with syscalls, but there should be a way to handle these without modifying psuedofiles.

**Describe the solution you'd like**

I think extending yaml with plugin interactions is ideal here.

First, we'd have a known set of functions that can be overloaded in Python (e.g. read, write, ioctl) and the ability to set the model for those to use a specific plugin.

For example:
```yaml
pseudofiles:
    /dev/asdf:
         read:
              model: zero
         ioctl:
              model: pluginA
```

Then in a pyplugin:

```python
class pluginA(PyPlugin):
      def ioctl(self, fd, cmd, arg):
            # implementation
```

Additionally, it might make sense to fully model a device in a pyplugin. We could do this with something like:

```yaml
pseudofiles:
    /dev/asdf: pluginA
```
and pluginA could simply override each of the methods
